name: plant_social
description: A plant-focused social messaging platform built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Network & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # Camera & Media
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  video_player: ^2.8.1
  photo_view: ^0.14.0
  
  # Real-time Communication
  web_socket_channel: ^2.4.0
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.2.1
  path_provider: ^2.1.1
  
  # Image Processing
  image: ^4.1.3
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  
  # Location
  geolocator: ^10.1.0
  
  # Contacts
  contacts_service: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  retrofit_generator: ^8.0.4
  json_serializable: ^6.7.1
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
  
  # fonts:
  #   - family: PlantSocial
  #     fonts:
  #       - asset: assets/fonts/PlantSocial-Regular.ttf
  #       - asset: assets/fonts/PlantSocial-Bold.ttf
  #         weight: 700