"""add_care_plans_v2_table

Revision ID: add_care_plans_v2
Revises: f9a8b7c6d5e4
Create Date: 2025-01-17 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_care_plans_v2'
down_revision = 'f9a8b7c6d5e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create care_plans_v2 table
    op.create_table('care_plans_v2',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('plant_id', sa.UUID(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('valid_from', sa.DateTime(), nullable=False),
        sa.Column('valid_to', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['plant_id'], ['user_plants.id'], name=op.f('fk_care_plans_v2_plant_id_user_plants')),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_care_plans_v2_user_id_users')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_care_plans_v2')),
        sa.UniqueConstraint('plant_id', 'version', name='uq_care_plan_plant_version')
    )
    
    # Create indexes for care_plans_v2
    op.create_index('ix_care_plans_v2_plant_id', 'care_plans_v2', ['plant_id'], unique=False)
    op.create_index('ix_care_plans_v2_user_id', 'care_plans_v2', ['user_id'], unique=False)
    op.create_index('ix_care_plans_v2_valid_from', 'care_plans_v2', ['valid_from'], unique=False)
    op.create_index('ix_care_plans_v2_created_at', 'care_plans_v2', ['created_at'], unique=False)
    op.create_index('ix_care_plans_v2_version', 'care_plans_v2', ['version'], unique=False)
    op.create_index('ix_care_plans_v2_active_plans', 'care_plans_v2', ['plant_id', 'valid_from', 'valid_to'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes
    op.drop_index('ix_care_plans_v2_active_plans', table_name='care_plans_v2')
    op.drop_index('ix_care_plans_v2_version', table_name='care_plans_v2')
    op.drop_index('ix_care_plans_v2_created_at', table_name='care_plans_v2')
    op.drop_index('ix_care_plans_v2_valid_from', table_name='care_plans_v2')
    op.drop_index('ix_care_plans_v2_user_id', table_name='care_plans_v2')
    op.drop_index('ix_care_plans_v2_plant_id', table_name='care_plans_v2')
    
    # Drop table
    op.drop_table('care_plans_v2')
    
    # ### end Alembic commands ###