"""add_user_roles_and_permissions

Revision ID: c306dca65370
Revises: 88316ca546cb
Create Date: 2025-06-29 11:00:41.179549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c306dca65370'
down_revision = '88316ca546cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_expert', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_moderator', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('expert_specialties', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('admin_permissions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin_permissions')
    op.drop_column('users', 'expert_specialties')
    op.drop_column('users', 'is_moderator')
    op.drop_column('users', 'is_expert')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###