"""Create initial schema with all models

Revision ID: eca90a7d28b5
Revises: e7c4ed08f749
Create Date: 2025-06-28 23:06:41.078273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca90a7d28b5'
down_revision = 'e7c4ed08f749'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###