"""Schemas package.

This module provides a string-only __all__ list to avoid eager imports
and prevent circular import issues during schema initialization.

To import schemas, use direct module imports:
    from app.schemas.user import UserPublicResponse
    from app.schemas.auth import Token
    etc.
"""

__all__ = [
    # Auth schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserRead",
    "UserInDB",
    "Token",
    "TokenData",
    "PasswordReset",
    "PasswordResetConfirm",
    "EmailVerification",
    "ChangePassword",
    "LoginRequest",
    "RefreshTokenRequest",
    "LogoutRequest",
    
    # User schemas
    "UserSchemaBase",
    "UserSchemaRead",
    "UserSearch",
    "UserPublicResponse",
    "UserSchemaUpdate",
    "UserProfile",
    "UserStats",
    "UserPreferences",
    "UserActivity",
    "UserBlock",
    "UserReport",
    "UserSearchFilters",
    "UserBatchOperation",
    
    # Message schemas
    "MessageType",
    "MessageStatus",
    "MessageBase",
    "MessageCreate",
    "MessageUpdate",
    "MessageRead",
    "MessageThread",
    "MessageReaction",
    "MessageReactionCreate",
    "MessageSearch",
    "MessageDeliveryStatus",
    "MessageBatch",
    "PlantIdentificationMessage",
    "PlantCareMessage",
    "MessageAnalytics",
    
    # Story schemas
    "StoryType",
    "StoryPrivacyLevel",
    "StoryBase",
    "StoryCreate",
    "StoryUpdate",
    "StoryRead",
    "StoryViewCreate",
    "StoryView",
    "StoryFeed",
    "StoryHighlight",
    "StoryHighlightCreate",
    "StoryHighlightUpdate",
    "PlantStoryData",
    "StoryAnalytics",
    "StorySearch",
    "StoryBatch",
    
    # Friendship schemas
    "FriendshipStatus",
    "FriendshipBase",
    "FriendRequestCreate",
    "FriendshipRead",
    "FriendshipUpdate",
    "FriendProfile",
    "FriendsList",
    "FriendRequestsList",
    "MutualFriends",
    "FriendshipStats",
    "FriendSuggestion",
    "FriendActivity",
    "BlockedUser",
    "FriendshipSearch",
    "FriendshipBatch",
    "FriendshipNotification",
    "FriendshipAnalytics",
    
    # Plant species schemas
    "PlantSpeciesBase",
    "PlantSpeciesCreate",
    "PlantSpeciesUpdate",
    "PlantSpeciesResponse",
    "PlantSpeciesListResponse",
    
    # User plant schemas
    "UserPlantBase",
    "UserPlantCreate",
    "UserPlantUpdate",
    "UserPlantResponse",
    "UserPlantListResponse",
    "PlantCareReminderResponse",
    
    # Plant care log schemas
    "PlantCareLogBase",
    "PlantCareLogCreate",
    "PlantCareLogUpdate",
    "PlantCareLogResponse",
    "PlantCareLogListResponse",
    "CareTypeStatsResponse",
    
    # Plant identification schemas
    "PlantIdentificationBase",
    "PlantIdentificationCreate",
    "PlantIdentificationUpdate",
    "PlantIdentificationResponse",
    "PlantIdentificationListResponse",
    "PlantIdentificationResultResponse",
    
    # Plant trade schemas
    "PlantTradeBase",
    "PlantTradeCreate",
    "PlantTradeUpdate",
    "PlantTradeResponse",
    "PlantTradeListResponse",
    "PlantTradeSearchRequest",
    "PlantTradeInterestRequest",
    
    # Plant question schemas
    "PlantQuestionBase",
    "PlantQuestionCreate",
    "PlantQuestionUpdate",
    "PlantAnswerBase",
    "PlantAnswerCreate",
    "PlantAnswerUpdate",
    "PlantAnswerResponse",
    "PlantQuestionResponse",
    "PlantQuestionListResponse",
    "PlantQuestionSearchRequest",
    "PlantAnswerVoteRequest",
    
    # Timelapse schemas
    "TrackingStatus",
    "ProcessingStatus",
    "MilestoneType",
    "DetectionMethod",
    "PhotoSchedule",
    "TrackingConfig",
    "PlantMeasurements",
    "HealthIndicators",
    "GrowthChanges",
    "AnomalyFlag",
    "GrowthAnalysis",
    "MilestoneTarget",
    "VideoOptions",
    "TimelapseSessionBase",
    "TimelapseSessionCreate",
    "TimelapseSessionUpdate",
    "TimelapseSessionResponse",
    "GrowthPhotoBase",
    "GrowthPhotoCreate",
    "GrowthPhotoResponse",
    "GrowthMilestoneBase",
    "GrowthMilestoneCreate",
    "GrowthMilestoneResponse",
    "TimelapseVideoRequest",
    "TimelapseVideoResponse",
    "TimelapseSessionListResponse",
    "GrowthPhotoListResponse",
    "GrowthMilestoneListResponse",
    
    # Telemetry schemas
    "LightReadingCreate",
    "BatchLightReadingRequest",
    "LightReadingResponse",
    "GrowthPhotoCreate",
    "GrowthMetricsSchema",
    "GrowthPhotoResponse",
    "CalibrationProfileCreate",
    "CalibrationProfileUpdate",
    "CalibrationProfileResponse",
    "BLEDeviceCreate",
    "BLEDeviceUpdate",
    "BLEDeviceResponse",
    "TelemetryQueryParams",
    "TelemetryStatsResponse",
    "TelemetryErrorResponse",
]